New take on a docker setup
CopenhagenCityArchives/kbhbilleder-docker pull request #2
Opened 2018-05-23 14:25 UTC by danquah

TODOs
- Update Readme
- tests

2018-05-23 14:55 UTC, tripox requested changes

2018-05-23 14:55 UTC, tripox commented on README.md
> +* Start indexing manually (starts automatically) with `docker-compose exec node run index all`
Should be removed

2018-05-23 14:55 UTC, tripox commented on development.env-dist
> +GITHUB_TOKEN=my-token-from-http://
Should be a real token or nothing. Maybe a comment above.

2018-05-23 14:55 UTC, tripox commented on scripts/index-all-assets.sh
> +docker-compose exec node npm run index all
This should be in the `README.md` and in a Makefile.

2018-05-23 14:55 UTC, tripox commented on docker/dev-env-Dockerfile
> +&& rm -rf /var/lib/apt/lists/* # Keeps the image size down
`apt-get clean`?

2018-05-24 12:49 UTC, stumpdk commented
@danquah Jeg strander når jeg kører docker-compose up. Jeg får følgende fejl: ``No such file or directory/env: bash`` fra Node-servicen

2018-06-06 08:23 UTC, tripox approved these changes

2018-06-06 08:23 UTC, tripox commented on README.md
> +2. Dory
Please drop a link to [the installation instructions](https://github.com/FreedomBen/dory#installation)

2018-06-06 10:11 UTC, merged